spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/market
    username: market_owner
    password: market_owner
  mail:
    username: reklaabderrahim@gmail.com
    password: iwuzxyxfzdhtlaat